spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=false

logging.level.com.openhtmltopdf=ERROR

app.importacao.chave=${APP_IMPORTACAO_CHAVE}

# Pool de conexões Hikari
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# Tempo máximo de vida de uma conexão
spring.datasource.hikari.max-lifetime=240000

# Tempo máximo que uma conexão pode ficar ociosa
spring.datasource.hikari.idle-timeout=120000

# Mantém conexões ociosas válidas
spring.datasource.hikari.keepalive-time=60000

# Tempo máximo para obter uma conexão do pool
spring.datasource.hikari.connection-timeout=30000

# Tempo máximo para validar uma conexão
spring.datasource.hikari.validation-timeout=5000